### ISSUE TITLE
Investigate and fix MG GeoNode down

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode-madagascar#2]
Currently getting a 500 error

![Screen Shot 2019-10-15 at 16 34 39](https://user-images.githubusercontent.com/10201533/66841547-22be9d00-ef6a-11e9-95ae-da6ca02e988e.jpg)

Previously a GeoNode error page

![Screen Shot 2019-10-14 at 09 43 11](https://user-images.githubusercontent.com/10201533/66841571-30742280-ef6a-11e9-856d-f3c26cc95eca.jpg)

The problem seems to have started a couple days ago

![Screen Shot 2019-10-15 at 16 37 10](https://user-images.githubusercontent.com/10201533/66841641-4aae0080-ef6a-11e9-8b08-03170ea190e2.jpg)

@simboss @afabiani can you please check?

**Comment by afabiani** [comment]
@cgiovando we are on it. It looks like the server has finished the inodes.

**Comment by fanevanjanahary** [comment]
It works now thanks @afabiani
