### ISSUE TITLE
Investigate Instability Issues

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode-madagascar#3]
Related to #2, this instance is fairly basic with a limited number of layers and users. We need to guarantee a minimum level of stability.

**Comment by simboss** [comment]
As reported by email:

1. there is simple backup mechanism that runs at night. It might make the server unresponsive for 15 or 20 mins 
2. the problem reported this weekend was due to dependency conflict for Postgis on Centos which was fixed today

For 2 there is no guarantee this won't happen again since not having a test or preprod server and working directly in PROD can make similar things happen.

**Comment by cgiovando** [comment]
@simboss the server is down again - can you please check? Assuming the issue is with core GeoNode code, can we test stability on a generic dev instance (e.g. demo.geonode.org) before deploying changes to this prod? If the issue is due to specific customization of this instance, then we may need to set up a dedicated staging environment.

**Comment by afabiani** [comment]
@cgiovando @simboss this is not a problem with the server. The DNS is not available anymore as far as I can see. The server is reachable by direct IP address 94.23.67.207

**Comment by simboss** [comment]
Thx @afabiani

**Comment by cgiovando** [comment]
The issue seems to be related to instability with the DNS.

@simboss do you have any idea what may be causing the issue with the registrar or where the DNS is managed?

http://whois.domaintools.com/resiliencemada.gov.mg shows:

![Screen Shot 2019-12-10 at 16 48 39](https://user-images.githubusercontent.com/10201533/70544825-fcce0700-1b6c-11ea-813f-97b2170b77a7.jpg)

And on https://lookup.icann.org/lookup we get:

![Screen Shot 2019-12-10 at 16 48 52](https://user-images.githubusercontent.com/10201533/70544871-10796d80-1b6d-11ea-99ef-6135dc4e3bed.jpg)

What would you recommend?

**Comment by simboss** [comment]
@cgiovando we were talking about this with alessandro this morning.
As you can see from the image below it is a problem with a name server that we presume it is owned by some PA in Madagascar.

![image_2019_12_09T17_01_27_123Z](https://user-images.githubusercontent.com/693880/70545778-67cc0d80-1b6e-11ea-8931-da7ab5b27cd1.png)

There is nothing we can do about it, I am afraid.
