### ISSUE TITLE
Document Down Monitoring and Alert System

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode-madagascar#4]
Related to #2 and #3 please provide documentation on how monitoring of the instance status is done and how notifications are delivered.

**Comment by simboss** [comment]
Hi @cgiovando,
we monitor geonode instaces using GeoHealthCheck to monitor multiple endpoints.

The current monitoring status, is captured [here](http://monitoring.geo-solutions.it/resources?lang=en&tag=GeoNode%3A+www.resiliencemada.gov.mg).
